---

image: ghcr.io/maxking/mailman-ci-runner


docs:
  script:
    - tox -e docs
lint:
  script:
    - tox -e lint

include:
  - project: "dependabot-gitlab/dependabot-standalone"
    file: ".gitlab-ci.yml"
